name: Split Repository
on:
  push:
    branch: [master]
  pull_request:
    types: [closed, merged]
    branch: [master]
    if: github.event.pull_request.merged == 'true'

jobs:
  split:
    name: Split Repository
    runs-on: ubuntu-latest
    container:
      image: php:7.4-alpine
      options: >-
        --tmpfs /tmp:exec
        --tmpfs /var/tmp:exec
    steps:
      - name: add required packages
        run: |
          apk add \
            git \
            bash
      - name: Checkout
        uses: actions/checkout@v1
      - name: runs splitsh
        run: |
          ./bin/split.sh